# Generated by Django 4.2.2 on 2023-07-15 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('franchise', '0005_remove_franchise_coordinates_timeslot'),
        ('products', '0002_franchiseitem_gross_weight_franchiseitem_net_weight_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now=True)),
                ('from_time', models.DateTimeField()),
                ('to_time', models.DateTimeField()),
                ('name', models.CharField(max_length=255)),
                ('franchise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='franchise.franchise')),
            ],
            options={
                'verbose_name': 'flas sale',
                'verbose_name_plural': 'flas sales',
                'db_table': 'promotions_flas_sale',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='TodayDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now=True)),
                ('from_time', models.DateTimeField()),
                ('to_time', models.DateTimeField()),
                ('name', models.CharField(max_length=255)),
                ('franchise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='franchise.franchise')),
            ],
            options={
                'verbose_name': 'todays deal',
                'verbose_name_plural': 'todays deals',
                'db_table': 'promotions_today_deal',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='TodayDealItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now=True)),
                ('special_price', models.IntegerField(blank=True, null=True)),
                ('franchise_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.franchiseitem')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotions.todaydeal')),
            ],
            options={
                'verbose_name': 'todays deal item',
                'verbose_name_plural': 'todays deal items',
                'db_table': 'promotions_today_deal_item',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='StaticBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('banner_type', models.CharField(choices=[('PR', 'Product'), ('CA', 'Category')], max_length=2)),
                ('model_id', models.IntegerField()),
                ('banner_image', models.FileField(blank=True, null=True, upload_to='')),
                ('franchise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='franchise.franchise')),
            ],
            options={
                'verbose_name': 'static banner',
                'verbose_name_plural': 'static banners',
                'db_table': 'promotions_static_banner',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('poster_type', models.CharField(choices=[('PR', 'Product'), ('CA', 'Category')], max_length=2)),
                ('model_id', models.IntegerField()),
                ('poster_image', models.FileField(blank=True, null=True, upload_to='')),
                ('franchise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='franchise.franchise')),
            ],
            options={
                'verbose_name': 'poster',
                'verbose_name_plural': 'posters',
                'db_table': 'promotions_poster',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('offer_code', models.CharField(max_length=100)),
                ('offer_model', models.CharField(choices=[('PV', 'Product Varient'), ('CA', 'Category'), ('PR', 'Product')], max_length=2)),
                ('model_id', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('is_percentage', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('maximum_discount', models.IntegerField(blank=True, null=True)),
                ('franchise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='franchise.franchise')),
            ],
            options={
                'verbose_name': 'offer',
                'verbose_name_plural': 'offers',
                'db_table': 'promotions_offer',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='FlashSaleItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now=True)),
                ('special_price', models.IntegerField(blank=True, null=True)),
                ('franchise_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.franchiseitem')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotions.flashsale')),
            ],
            options={
                'verbose_name': 'flas sale item',
                'verbose_name_plural': 'flas sale items',
                'db_table': 'promotions_flas_sale_item',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('banner_type', models.CharField(choices=[('PR', 'Product'), ('CA', 'Category')], max_length=2)),
                ('model_id', models.IntegerField()),
                ('banner_image', models.FileField(blank=True, null=True, upload_to='')),
                ('franchise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='franchise.franchise')),
            ],
            options={
                'verbose_name': 'banner',
                'verbose_name_plural': 'banners',
                'db_table': 'promotions_banner',
                'ordering': ('-id',),
            },
        ),
    ]
