# Generated by Django 4.2.2 on 2023-07-18 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customer_current_address_alter_cart_flash_item_and_more'),
        ('products', '0003_franchiseitem_delivery_distance'),
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todaydealitems',
            name='franchise_item',
        ),
        migrations.RemoveField(
            model_name='todaydealitems',
            name='sale',
        ),
        migrations.RemoveField(
            model_name='flashsale',
            name='from_time',
        ),
        migrations.RemoveField(
            model_name='flashsale',
            name='name',
        ),
        migrations.RemoveField(
            model_name='flashsale',
            name='to_time',
        ),
        migrations.RemoveField(
            model_name='todaydeal',
            name='from_time',
        ),
        migrations.RemoveField(
            model_name='todaydeal',
            name='name',
        ),
        migrations.RemoveField(
            model_name='todaydeal',
            name='to_time',
        ),
        migrations.AddField(
            model_name='flashsale',
            name='franchise_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.franchiseitem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flashsale',
            name='special_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todaydeal',
            name='franchise_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.franchiseitem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todaydeal',
            name='special_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='FlashSaleItems',
        ),
        migrations.DeleteModel(
            name='TodayDealItems',
        ),
    ]
