# Generated by Django 4.2.2 on 2023-07-15 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('franchise', '0005_remove_franchise_coordinates_timeslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now=True)),
                ('delivery_type', models.CharField(choices=[('TS', 'Time Slot'), ('IN', 'Instant')], max_length=2)),
                ('franchise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='franchise.franchise')),
                ('time_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='franchise.timeslot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'delivery',
                'verbose_name_plural': 'deliverys',
                'db_table': 'delivery_delivery',
                'ordering': ('id',),
            },
        ),
    ]
