# Generated by Django 4.2.2 on 2023-06-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_otpverifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_delivery',
            field=models.BooleanField(default=False, verbose_name='Is delivery'),
        ),
    ]
