# Generated by Django 4.2.2 on 2023-06-14 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('franchise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Franchise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256)),
                ('address', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'verbose_name': 'franchise',
                'verbose_name_plural': 'franchises',
                'db_table': 'franchise_franchise',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='franchiseuser',
            name='franchise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='franchise.franchise'),
            preserve_default=False,
        ),
    ]
