# Generated by Django 4.2.2 on 2023-06-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchise', '0003_alter_franchise_options_alter_franchiseuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchise',
            name='base_charge',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='franchise',
            name='base_distance',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='franchise',
            name='coordinates',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='franchise',
            name='extra_charge',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='franchise',
            name='extra_distance',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='franchise',
            name='free_delivery_cart',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='franchise',
            name='instant_delivery',
            field=models.BooleanField(default=True),
        ),
    ]
