# Generated by Django 4.2.2 on 2023-07-15 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('franchise', '0004_franchise_base_charge_franchise_base_distance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='franchise',
            name='coordinates',
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now=True)),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('franchise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='franchise.franchise')),
            ],
            options={
                'verbose_name': 'time slot',
                'verbose_name_plural': 'time slots',
                'db_table': 'franchise_time_slot',
                'ordering': ('-id',),
            },
        ),
    ]
