# Generated by Django 4.2.2 on 2023-07-15 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchise', '0005_remove_franchise_coordinates_timeslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchise',
            name='delivery_distance',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
