# Generated by Django 4.2.2 on 2023-07-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchise', '0006_franchise_delivery_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchise',
            name='district',
            field=models.CharField(default='Malappuram', max_length=256),
        ),
    ]
