# Generated by Django 4.2.2 on 2023-08-12 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now=True)),
                ('company', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('address_line1', models.TextField()),
                ('address_line2', models.TextField()),
                ('district', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=25)),
                ('pincode', models.CharField(max_length=25)),
                ('privacy', models.CharField(max_length=99)),
                ('about', models.CharField(max_length=99)),
                ('terms', models.CharField(max_length=99)),
                ('refund', models.CharField(max_length=99)),
            ],
            options={
                'verbose_name': 'manager contact',
                'verbose_name_plural': 'manager contacts',
                'db_table': 'manager_manager_contact',
                'ordering': ('id',),
            },
        ),
    ]
