# Generated by Django 4.1.7 on 2023-02-17 18:28

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'about',
                'verbose_name_plural': 'abouts',
                'db_table': 'cfresh_about',
                'ordering': ['-id'],
            },
        ),
    ]
