# Generated by Django 4.2.2 on 2023-07-14 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('franchise', '0004_franchise_base_charge_franchise_base_distance_and_more'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True)),
                ('address_type', models.CharField(choices=[('HM', 'Home'), ('WO', 'Work'), ('HT', 'Hotel'), ('OT', 'Other')], max_length=2)),
                ('address', models.TextField()),
                ('floor', models.CharField(blank=True, max_length=100, null=True)),
                ('street', models.CharField(blank=True, max_length=100, null=True)),
                ('land_mark', models.CharField(blank=True, max_length=100, null=True)),
                ('building_name', models.CharField(blank=True, max_length=100, null=True)),
                ('building_number', models.CharField(blank=True, max_length=100, null=True)),
                ('block_name', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('active_address', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'address',
                'verbose_name_plural': 'addresses',
                'db_table': 'customer_address',
                'ordering': ('-id',),
            },
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ('-id',), 'verbose_name': 'customer', 'verbose_name_plural': 'customers'},
        ),
        migrations.AddField(
            model_name='customer',
            name='current_franchise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='franchise.franchise'),
        ),
        migrations.AddField(
            model_name='customer',
            name='reward_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.ManyToManyField(to='customers.customeraddress'),
        ),
    ]
