# Generated by Django 4.2.2 on 2023-07-18 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
        ('customers', '0003_customer_bag_value_customer_wallet_amount_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='current_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customeraddress'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='flash_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='promotions.flashsale'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='today_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='promotions.todaydeal'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.ManyToManyField(related_name='customer_address', to='customers.customeraddress'),
        ),
    ]
