# Generated by Django 4.2.2 on 2023-07-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customer_current_address_alter_cart_flash_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeraddress',
            name='block_name',
        ),
        migrations.RemoveField(
            model_name='customeraddress',
            name='building_name',
        ),
        migrations.RemoveField(
            model_name='customeraddress',
            name='building_number',
        ),
        migrations.RemoveField(
            model_name='customeraddress',
            name='floor',
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.ManyToManyField(blank=True, null=True, related_name='customer_address', to='customers.customeraddress'),
        ),
    ]
