# Generated by Django 4.2.2 on 2023-08-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_remove_customeraddress_active_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddress',
            name='address_type',
            field=models.CharField(max_length=10),
        ),
    ]
