# Generated by Django 4.2.2 on 2023-08-03 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_franchiseitem_delivery_distance'),
        ('franchise', '0007_franchise_district'),
        ('customers', '0008_alter_customeraddress_address_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_amount',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='franchise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='franchise.franchise'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='item_type',
            field=models.CharField(choices=[('FI', 'Franchise Item'), ('VR', 'Variant'), ('TD', 'Todays Deal'), ('FS', 'Flash Sale')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.franchiseitem'),
        ),
    ]
