# Generated by Django 4.2.2 on 2023-08-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_cart_cart_amount_cart_franchise_cart_item_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_ordered',
            field=models.BooleanField(default=False),
        ),
    ]
