# Generated by Django 4.2.2 on 2023-08-06 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('promotions', '0002_remove_todaydealitems_franchise_item_and_more'),
        ('customers', '0010_cart_is_ordered'),
        ('delivery', '0001_initial'),
        ('franchise', '0007_franchise_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now=True)),
                ('order_id', models.CharField(max_length=100)),
                ('payment_status', models.CharField(choices=[('TD', 'To be done'), ('IN', 'Initiated'), ('CO', 'Completed'), ('FA', 'Failed'), ('RF', 'Refused By Customer')], max_length=2)),
                ('order_status', models.CharField(choices=[('IN', 'Initiated'), ('PL', 'Placed'), ('IP', 'In progress'), ('CO', 'Completed'), ('CA', 'Cancelled')], max_length=2)),
                ('actual_price', models.IntegerField()),
                ('offer_price', models.IntegerField(default=0)),
                ('final_price', models.IntegerField()),
                ('cancelled_by', models.CharField(blank=True, choices=[('CS', 'Customer'), ('DA', 'Delivery Agent'), ('FA', 'Franchise Admin')], max_length=2, null=True)),
                ('delivery_type', models.CharField(choices=[('TS', 'Time Slot'), ('IN', 'Instant')], max_length=2)),
                ('delivery_day', models.CharField(blank=True, choices=[('TD', 'Today'), ('TM', 'Tomorrow')], max_length=2, null=True)),
                ('delivery_charge', models.IntegerField(default=0)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customeraddress')),
                ('cart_items', models.ManyToManyField(to='customers.cart')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('delivery_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.deliveryagent')),
                ('franchise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='franchise.franchise')),
                ('offer_applied', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='promotions.offer')),
                ('time_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='franchise.timeslot')),
            ],
        ),
    ]
