# Generated by Django 4.2.2 on 2023-08-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('COD', 'Cash on Delivery'), ('RZP', 'Razorpay'), ('WLT', 'Wallet')], max_length=3, null=True),
        ),
    ]
