# Generated by Django 4.2.2 on 2023-08-13 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_payment_method'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-id',), 'verbose_name': 'order', 'verbose_name_plural': 'orders'},
        ),
        migrations.AlterModelTable(
            name='order',
            table='orders_order',
        ),
    ]
