# Generated by Django 4.2.2 on 2023-07-15 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchiseitem',
            name='gross_weight',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='franchiseitem',
            name='net_weight',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variantdetail',
            name='gross_weight',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variantdetail',
            name='net_weight',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
