# Generated by Django 4.2.2 on 2023-07-15 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_franchiseitem_gross_weight_franchiseitem_net_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchiseitem',
            name='delivery_distance',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
