# Generated by Django 4.2.2 on 2023-07-19 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_franchiseitem_delivery_distance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variantdetail',
            name='item_variant',
        ),
        migrations.DeleteModel(
            name='ItemVariant',
        ),
    ]
