# Generated by Django 4.2.2 on 2023-07-20 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('franchise', '0006_franchise_delivery_distance'),
        ('products', '0004_remove_variantdetail_item_variant_delete_itemvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantdetail',
            name='franchise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='franchise.franchise'),
            preserve_default=False,
        ),
    ]
