# Generated by Django 4.2.2 on 2023-07-20 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_variantdetail_franchise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='franchiseitem',
            name='variations',
        ),
        migrations.RemoveField(
            model_name='variantdetail',
            name='gross_weight',
        ),
        migrations.RemoveField(
            model_name='variantdetail',
            name='net_weight',
        ),
        migrations.RemoveField(
            model_name='variantdetail',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='variantdetail',
            name='unit_quantity',
        ),
        migrations.AddField(
            model_name='variantdetail',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.franchiseitem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='franchiseitem',
            name='unit',
            field=models.CharField(choices=[('KG', 'KG'), ('LI', 'LI'), ('G', 'G')], max_length=2),
        ),
    ]
