# Generated by Django 4.2.2 on 2023-08-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_franchiseitem_delivery_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchiseitem',
            name='flash_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='franchiseitem',
            name='todays_deal',
            field=models.BooleanField(default=False),
        ),
    ]
